const express = require("express");
const cors = require("cors");
const pool = require("./db");
require("dotenv").config();

const app = express();
const PORT = process.env.PORT || 5050;

function sanitisePatient(data) {
  // 1. clone so we don’t mutate req.body directly
  const clean = { ...data };

  // 2. list of numeric fields in your form
  const numericKeys = [
    "age", "height_cm", "weight_kg",
    "waist_circumference", "bp_systolic", "bp_diastolic",
    "ast", "alt", "ggt", "triglycerides", "hdl_cholesterol",
    "hba1c", "fasting_glucose", "fibroscan_kpa"
  ];

  for (const k in clean) {
    if (clean[k] === "") {
      // turn "" into null
      clean[k] = null;
    } else if (numericKeys.includes(k)) {
      // turn "120" into 120  (or leave null as-is)
      clean[k] = Number(clean[k]);
    }
  }
  return clean;
}

const allowedOrigin = process.env.ALLOWED_ORIGIN || "*";

app.use(cors({
  origin: allowedOrigin,
  credentials: true,
}));

app.use(express.json());


app.post("/submit", async (req, res) => {
  try {

    const data = sanitisePatient(req.body);
    
    // pg needs a *string* for jsonb columns
    data.report_files = JSON.stringify(data.report_files ?? []);

    const query = `
      INSERT INTO patients (
        name, mobile, date_of_birth, age, state, sex, height_cm, weight_kg, waist_circumference,
        bp_systolic, bp_diastolic, ast, alt, ggt,
        triglycerides, hdl_cholesterol, hba1c, fasting_glucose,
        fibroscan_kpa, biopsy_result, diagnosis_group, report_files
      ) VALUES (
        $1, $2, $3, $4, $5,
        $6, $7, $8, $9, $10,
        $11, $12, $13, $14,
        $15, $16, $17, $18, 
        $19, $20, $21, $22::jsonb
      )
    `;

    const values = [
      data.name, data.mobile, data.date_of_birth, data.age, data.state,
      data.sex, data.height_cm, data.weight_kg, data.waist_circumference,
      data.bp_systolic, data.bp_diastolic, data.ast, data.alt, data.ggt,
      data.triglycerides, data.hdl_cholesterol, data.hba1c, data.fasting_glucose,
      data.fibroscan_kpa, data.biopsy_result, data.diagnosis_group, data.report_files
    ];

    await pool.query(query, values);
    console.log("Received data:", data);
    res.status(200).send("Patient data stored successfully.");
  } catch (err) {
    console.error("Error storing data:", err);
    res.status(500).send("Failed to insert patient data.");
  }
});

app.listen(PORT, () => {
  console.log(`Server running on http://localhost:${PORT}`);
});


// Begin GCS Cloud Connect.

const { Storage } = require("@google-cloud/storage");
const path = require("path");

/*const storage = new Storage({
  keyFilename: path.join(__dirname, "gcs-key.json"), 
});
*/

const storage = new Storage({
  projectId: process.env.GCP_PROJECT_ID,
  credentials: {
    client_email: process.env.GCP_CLIENT_EMAIL,
    private_key: process.env.GCP_PRIVATE_KEY.replace(/\\n/g, '\n'),
  },
});

const bucketName = "masld-reports";
const bucket = storage.bucket(bucketName);

// End GCS Cloud Connect.

// Begin GCS Upload code.
const multer = require("multer");
const upload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 10 * 1024 * 1024 },  // 10 MB per file
});

/*Start Creation of table */
app.get('/create-table', async (req, res) => {
  try {
    await pool.query(`
      CREATE TABLE patients (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT,
        mobile TEXT,
        date_of_birth DATE,
        age INTEGER,
        sex TEXT,
        state TEXT,
        height_cm NUMERIC,
        weight_kg NUMERIC,
        waist_circumference NUMERIC,
        bp_systolic INTEGER,
        bp_diastolic INTEGER,
        ast NUMERIC,
        alt NUMERIC,
        ggt NUMERIC,
        triglycerides NUMERIC,
        hdl_cholesterol NUMERIC,
        hba1c NUMERIC,
        fasting_glucose NUMERIC,
        fibroscan_kpa NUMERIC,
        biopsy_result TEXT,
        diagnosis_group TEXT,
        report_files jsonb DEFAULT '[]'::jsonb
      );
    `);
    res.send("✅ patients table created.");
  } catch (err) {
    console.error(err);
    res.status(500).send("Error creating table.");
  }
});
/*End Creation of table */

app.post('/upload-multiple', upload.array('reports'), async (req, res) => {
  try {
    /* ---------- sanity checks ---------- */
    const files = req.files;                 // array from Multer
    const typesRaw = req.body.types;         // string → JSON.parse below

    if (!files?.length) {
      return res.status(400).json({ uploadedFiles: [] });
    }
    if (!typesRaw) {
      return res.status(400).json({ error: '"types" field missing.' });
    }

    let types;
    try {
      types = JSON.parse(typesRaw);
    } catch {
      return res.status(400).json({ error: '"types" is not valid JSON.' });
    }

    if (files.length !== types.length) {
      return res.status(400).json({
        error: `Mismatch: ${files.length} files, ${types.length} types.`,
      });
    }

    /* ---------- upload each file ---------- */
    const uploadedFiles = await Promise.all(
      files.map((file, i) => uploadOne(file, types[i]))
    );

    return res.status(200).json({ uploadedFiles });
  } catch (err) {
    console.error('Upload error:', err);
    return res.status(500).json({ error: 'Upload failed. See server logs.' });
  }
});

/* helper stores file.buffer directly in GCS */
async function uploadOne(file, givenType) {
  const blob = bucket.file(`${Date.now()}-${file.originalname}`);
  await blob.save(file.buffer, {
    resumable: false,
    contentType: file.mimetype,
  });
  return {
    file_url: `https://storage.googleapis.com/${bucket.name}/${blob.name}`,
    file_type: givenType,
  };
}
// End GCS Upload code.